package entity;
// Generated May 25, 2018 11:12:04 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private Book book;
     private OrderHistory orderHistory;
     private int quanlity;

    public OrderDetail() {
    }

    public OrderDetail(OrderDetailId id, Book book, OrderHistory orderHistory, int quanlity) {
       this.id = id;
       this.book = book;
       this.orderHistory = orderHistory;
       this.quanlity = quanlity;
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public OrderHistory getOrderHistory() {
        return this.orderHistory;
    }
    
    public void setOrderHistory(OrderHistory orderHistory) {
        this.orderHistory = orderHistory;
    }
    public int getQuanlity() {
        return this.quanlity;
    }
    
    public void setQuanlity(int quanlity) {
        this.quanlity = quanlity;
    }




}


