package entity;
// Generated May 25, 2018 11:12:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderHistory generated by hbm2java
 */
public class OrderHistory  implements java.io.Serializable {


     private int orderId;
     private User user;
     private Date orderDate;
     private Date deliveryDate;
     private boolean checkOut;
     private boolean isCart;
     private Set orderDetails = new HashSet(0);

    public OrderHistory() {
    }

	
    public OrderHistory(int orderId, Date orderDate, boolean checkOut, boolean isCart) {
        this.orderId = orderId;
        this.orderDate = orderDate;
        this.checkOut = checkOut;
        this.isCart = isCart;
    }
    public OrderHistory(int orderId, User user, Date orderDate, Date deliveryDate, boolean checkOut, boolean isCart, Set orderDetails) {
       this.orderId = orderId;
       this.user = user;
       this.orderDate = orderDate;
       this.deliveryDate = deliveryDate;
       this.checkOut = checkOut;
       this.isCart = isCart;
       this.orderDetails = orderDetails;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public boolean isCheckOut() {
        return this.checkOut;
    }
    
    public void setCheckOut(boolean checkOut) {
        this.checkOut = checkOut;
    }
    public boolean isIsCart() {
        return this.isCart;
    }
    
    public void setIsCart(boolean isCart) {
        this.isCart = isCart;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


