package entity;
// Generated May 6, 2018 1:09:40 PM by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class User {

    private String username;
    private String password;
    private String name;
    private String email;
    private String role;
    private String address;
    private String phone;
    private boolean active;

    public User() {
        this.active = true;
        this.role = "User";
    }

    public User(String username, String password, String name, String address, String phone, boolean active) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.active = active;
    }

    public User(String username, String password, String name, String email, String role, String address, String phone, boolean active) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
        this.role = role;
        this.address = address;
        this.phone = phone;
        this.active = active;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}
